import type { MapPlace } from "@/types/map";

export const mapPlaces: MapPlace[] = [
  // ─── Buenos Aires — Palermo Soho ─────────────────────────────────────────
  {
    id: "ba-plaza-serrano",
    nameHe: "פלאזה סראנו",
    nameEn: "Plaza Serrano",
    city: "Buenos Aires", country: "Argentina",
    area: "Palermo Soho", areaHe: "פלרמו סוהו",
    category: "park", categoryHe: "פארק",
    tags: ["כיכר", "קפות", "ברים", "חנויות"],
    descriptionHe: "כיכר פופולרית בפלרמו — קפות, ברים וחנויות בוטיק",
    rating: 4.4, priority: "medium",
    googleMapsUrl: "https://maps.google.com/?q=Plaza+Serrano+Buenos+Aires",
    coordinates: { lat: -34.5882, lng: -58.4347 },
    source: "google-favorites",
  },
  {
    id: "ba-el-preferido",
    nameHe: "אל פרפרידו דה פלרמו",
    nameEn: "El Preferido de Palermo",
    city: "Buenos Aires", country: "Argentina",
    area: "Palermo Soho", areaHe: "פלרמו סוהו",
    category: "restaurant", categoryHe: "מסעדה",
    tags: ["ארגנטינאי", "קלאסי", "מומלץ"],
    descriptionHe: "מסעדה ארגנטינאית קלאסית בפלרמו — 4.4 ⭐",
    rating: 4.4, priority: "high",
    googleMapsUrl: "https://maps.google.com/?q=El+Preferido+de+Palermo+Buenos+Aires",
    coordinates: { lat: -34.5874, lng: -58.4299 },
    relevantDays: [1, 2, 3, 4, 5],
    source: "google-favorites",
  },
  {
    id: "ba-palermo-soho",
    nameHe: "פלרמו סוהו",
    nameEn: "Palermo Soho",
    city: "Buenos Aires", country: "Argentina",
    area: "Palermo Soho", areaHe: "פלרמו סוהו",
    category: "neighborhood", categoryHe: "שכונה",
    tags: ["ברים", "מסעדות", "חנויות", "לילה"],
    descriptionHe: "האזור הצעיר והתוסס — ברים, מסעדות, חנויות ואורבניות",
    priority: "high",
    googleMapsUrl: "https://maps.google.com/?q=Palermo+Soho+Buenos+Aires",
    coordinates: { lat: -34.5875, lng: -58.4283 },
    relevantDays: [1, 2, 3, 4, 5],
    source: "trip-plan",
  },
  {
    id: "ba-boticario",
    nameHe: "בוטיקריו",
    nameEn: "Boticario",
    city: "Buenos Aires", country: "Argentina",
    area: "Palermo Soho", areaHe: "פלרמו סוהו",
    category: "bar", categoryHe: "בר",
    tags: ["קוקטיילים", "מומלץ", "אווירה"],
    descriptionHe: "בר קוקטיילים — 4.5 ⭐",
    rating: 4.5, priority: "high",
    googleMapsUrl: "https://maps.google.com/?q=Boticario+Buenos+Aires",
    coordinates: { lat: -34.5869, lng: -58.4312 },
    relevantDays: [1, 2, 3, 4, 5],
    source: "google-favorites",
  },
  {
    id: "ba-tres-monos",
    nameHe: "טרס מונוס",
    nameEn: "Tres Monos",
    city: "Buenos Aires", country: "Argentina",
    area: "Palermo Soho", areaHe: "פלרמו סוהו",
    category: "bar", categoryHe: "בר",
    tags: ["בר", "פלרמו"],
    descriptionHe: "בר ידוע בפלרמו — 4.4 ⭐",
    rating: 4.4, priority: "high",
    googleMapsUrl: "https://maps.google.com/?q=Tres+Monos+Buenos+Aires",
    coordinates: { lat: -34.5863, lng: -58.4291 },
    source: "google-favorites",
  },
  {
    id: "ba-presidente-bar",
    nameHe: "פרסידנטה בר",
    nameEn: "Presidente Bar",
    city: "Buenos Aires", country: "Argentina",
    area: "Palermo Soho", areaHe: "פלרמו סוהו",
    category: "bar", categoryHe: "בר",
    tags: ["קוקטיילים"],
    descriptionHe: "בר קוקטיילים — 4.4 ⭐",
    rating: 4.4, priority: "high",
    googleMapsUrl: "https://maps.google.com/?q=Presidente+Bar+Buenos+Aires",
    coordinates: { lat: -34.5857, lng: -58.4321 },
    source: "google-favorites",
  },
  {
    id: "ba-fogon-asado",
    nameHe: "פוגון אסדו",
    nameEn: "Fogón Asado",
    city: "Buenos Aires", country: "Argentina",
    area: "Palermo Soho", areaHe: "פלרמו סוהו",
    category: "restaurant", categoryHe: "מסעדה",
    tags: ["פארייה", "בשר", "מומלץ"],
    descriptionHe: "פארייה — 4.7 ⭐",
    rating: 4.7, priority: "high",
    googleMapsUrl: "https://maps.google.com/?q=Fogón+Asado+Buenos+Aires",
    coordinates: { lat: -34.5836, lng: -58.4261 },
    relevantDays: [1, 2, 3, 4, 5],
    source: "google-favorites",
  },
  {
    id: "ba-el-mercado",
    nameHe: "אל מרקדו",
    nameEn: "El Mercado",
    city: "Buenos Aires", country: "Argentina",
    area: "Palermo Soho", areaHe: "פלרמו סוהו",
    category: "restaurant", categoryHe: "מסעדה",
    tags: ["גריל", "בשר"],
    descriptionHe: "גריל ומסעדה — 4.7 ⭐",
    rating: 4.7, priority: "medium",
    googleMapsUrl: "https://maps.google.com/?q=El+Mercado+Buenos+Aires",
    coordinates: { lat: -34.5841, lng: -58.4278 },
    source: "google-favorites",
  },
  {
    id: "ba-victor-bar",
    nameHe: "ויקטור אודיו בר",
    nameEn: "Victor Audio Bar",
    city: "Buenos Aires", country: "Argentina",
    area: "Palermo Soho", areaHe: "פלרמו סוהו",
    category: "restaurant", categoryHe: "מסעדה",
    tags: ["גריל", "בר", "מוזיקה"],
    descriptionHe: "גריל ובר — 4.7 ⭐",
    rating: 4.7, priority: "medium",
    googleMapsUrl: "https://maps.google.com/?q=Victor+Audio+Bar+Buenos+Aires",
    coordinates: { lat: -34.5828, lng: -58.4245 },
    source: "google-favorites",
  },
  {
    id: "ba-piso15",
    nameHe: "פיסו 15 סקיי בר",
    nameEn: "Piso 15 Sky Bar",
    city: "Buenos Aires", country: "Argentina",
    area: "Palermo Soho", areaHe: "פלרמו סוהו",
    category: "bar", categoryHe: "בר",
    tags: ["בר גג", "נוף", "קוקטיילים"],
    descriptionHe: "בר גג עם נוף לעיר — 4.5 ⭐",
    rating: 4.5, priority: "high",
    googleMapsUrl: "https://maps.google.com/?q=Piso+15+Sky+Bar+Buenos+Aires",
    coordinates: { lat: -34.5822, lng: -58.4219 },
    source: "google-favorites",
  },

  // ─── Buenos Aires — Recoleta ──────────────────────────────────────────────
  {
    id: "ba-recoleta",
    nameHe: "רקולטה",
    nameEn: "Recoleta",
    city: "Buenos Aires", country: "Argentina",
    area: "Recoleta", areaHe: "רקולטה",
    category: "neighborhood", categoryHe: "שכונה",
    tags: ["אלגנטי", "טיול", "ארכיטקטורה"],
    descriptionHe: "השדרה האלגנטית — ארכיטקטורה ובוטיקים",
    priority: "high",
    googleMapsUrl: "https://maps.google.com/?q=Recoleta+Buenos+Aires",
    coordinates: { lat: -34.5883, lng: -58.3932 },
    relevantDays: [1, 2, 3, 4, 5],
    source: "trip-plan",
  },
  {
    id: "ba-recoleta-cemetery",
    nameHe: "בית הקברות רקולטה",
    nameEn: "Cementerio de la Recoleta",
    city: "Buenos Aires", country: "Argentina",
    area: "Recoleta", areaHe: "רקולטה",
    category: "attraction", categoryHe: "אטרקציה",
    tags: ["אטרקציה", "היסטוריה", "אוויטה"],
    descriptionHe: "אחת האטרקציות המפורסמות בעיר — קברה של אוויטה פרון",
    rating: 4.3, priority: "high",
    googleMapsUrl: "https://maps.google.com/?q=Cementerio+de+la+Recoleta+Buenos+Aires",
    coordinates: { lat: -34.5877, lng: -58.3929 },
    relevantDays: [1, 2, 3, 4, 5],
    source: "google-favorites",
  },
  {
    id: "ba-mayor-seeber",
    nameHe: "כיכר מאיור סיבר",
    nameEn: "Mayor Seeber Square",
    city: "Buenos Aires", country: "Argentina",
    area: "Recoleta", areaHe: "רקולטה",
    category: "park", categoryHe: "פארק",
    tags: ["כיכר", "פארק"],
    descriptionHe: "כיכר ופארק — 4.5 ⭐",
    rating: 4.5, priority: "medium",
    googleMapsUrl: "https://maps.google.com/?q=Mayor+Seeber+Square+Buenos+Aires",
    coordinates: { lat: -34.5848, lng: -58.3936 },
    source: "google-favorites",
  },

  // ─── Buenos Aires — San Telmo ─────────────────────────────────────────────
  {
    id: "ba-san-telmo",
    nameHe: "סן טלמו",
    nameEn: "San Telmo",
    city: "Buenos Aires", country: "Argentina",
    area: "San Telmo", areaHe: "סן טלמו",
    category: "neighborhood", categoryHe: "שכונה",
    tags: ["אותנטי", "טנגו", "שוק", "ישן"],
    descriptionHe: "השכונה האותנטית — רחובות עתיקים, טנגו ושוק מקומי",
    priority: "high",
    googleMapsUrl: "https://maps.google.com/?q=San+Telmo+Buenos+Aires",
    coordinates: { lat: -34.6213, lng: -58.3731 },
    relevantDays: [1, 2, 3, 4, 5],
    source: "trip-plan",
  },

  // ─── Buenos Aires — Puerto Madero ─────────────────────────────────────────
  {
    id: "ba-puerto-madero",
    nameHe: "פוארטו מדרו",
    nameEn: "Puerto Madero",
    city: "Buenos Aires", country: "Argentina",
    area: "Puerto Madero", areaHe: "פוארטו מדרו",
    category: "neighborhood", categoryHe: "שכונה",
    tags: ["נמל", "טיילת", "מסעדות"],
    descriptionHe: "רובע הנמל המודרני — טיילת ומסעדות",
    priority: "medium",
    googleMapsUrl: "https://maps.google.com/?q=Puerto+Madero+Buenos+Aires",
    coordinates: { lat: -34.6175, lng: -58.3627 },
    source: "trip-plan",
  },
  {
    id: "ba-buquebus",
    nameHe: "מסוף בוקבוס פוארטו מדרו",
    nameEn: "Terminal Fluvial Buquebus Puerto Madero",
    city: "Buenos Aires", country: "Argentina",
    area: "Puerto Madero", areaHe: "פוארטו מדרו",
    category: "transport", categoryHe: "תחבורה",
    tags: ["ספינה", "אורוגוואי", "קולוניה", "תחבורה"],
    descriptionHe: "מסוף המעבורת לקולוניה דל סקרמנטו, אורוגוואי",
    rating: 3.5, priority: "high",
    googleMapsUrl: "https://maps.google.com/?q=Terminal+Fluvial+Buquebus+Puerto+Madero",
    coordinates: { lat: -34.6189, lng: -58.3621 },
    relevantDays: [4, 5],
    source: "google-favorites",
  },

  // ─── Buenos Aires — La Boca ───────────────────────────────────────────────
  {
    id: "ba-la-boca",
    nameHe: "לה בוקה",
    nameEn: "La Boca",
    city: "Buenos Aires", country: "Argentina",
    area: "La Boca", areaHe: "לה בוקה",
    category: "neighborhood", categoryHe: "שכונה",
    tags: ["בוקה ג'וניורס", "קמיניטו", "צבעוני"],
    descriptionHe: "שכונת לה בוקה — בוקה ג'וניורס וקמיניטו",
    priority: "medium",
    googleMapsUrl: "https://maps.google.com/?q=La+Boca+Buenos+Aires",
    coordinates: { lat: -34.6342, lng: -58.3627 },
    source: "trip-plan",
  },
  {
    id: "ba-caminito",
    nameHe: "קמיניטו",
    nameEn: "Caminito",
    city: "Buenos Aires", country: "Argentina",
    area: "La Boca", areaHe: "לה בוקה",
    category: "attraction", categoryHe: "אטרקציה",
    tags: ["צבעוני", "תיירות", "אייקוני"],
    descriptionHe: "רחוב הצבעים האייקוני בלה בוקה — 4.5 ⭐",
    rating: 4.5, priority: "high",
    googleMapsUrl: "https://maps.google.com/?q=Caminito+Buenos+Aires",
    coordinates: { lat: -34.6364, lng: -58.3632 },
    relevantDays: [1, 2, 3, 4, 5],
    source: "google-favorites",
  },

  // ─── Buenos Aires — Centro / Microcentro ──────────────────────────────────
  {
    id: "ba-obelisco",
    nameHe: "האובליסק",
    nameEn: "Obelisco de Buenos Aires",
    city: "Buenos Aires", country: "Argentina",
    area: "Centro", areaHe: "מרכז העיר",
    category: "attraction", categoryHe: "אטרקציה",
    tags: ["אייקוני", "סמל", "היסטוריה"],
    descriptionHe: "סמל בואנוס איירס — 4.6 ⭐",
    rating: 4.6, priority: "high",
    googleMapsUrl: "https://maps.google.com/?q=Obelisco+de+Buenos+Aires",
    coordinates: { lat: -34.6037, lng: -58.3816 },
    relevantDays: [1, 2, 3, 4, 5],
    source: "google-favorites",
  },
  {
    id: "ba-calle-florida",
    nameHe: "רחוב פלורידה",
    nameEn: "Calle Florida",
    city: "Buenos Aires", country: "Argentina",
    area: "Centro", areaHe: "מרכז העיר",
    category: "shopping", categoryHe: "קניות",
    tags: ["קניות", "הולכי רגל", "אווירה"],
    descriptionHe: "רחוב הולכי הרגל המפורסם — קניות ואווירה — 4.5 ⭐",
    rating: 4.5, priority: "high",
    googleMapsUrl: "https://maps.google.com/?q=Calle+Florida+Buenos+Aires",
    coordinates: { lat: -34.6082, lng: -58.3738 },
    relevantDays: [1, 2, 3, 4, 5],
    source: "google-favorites",
  },
  {
    id: "ba-av-santa-fe",
    nameHe: "אבנידה סנטה פה",
    nameEn: "Avenida Santa Fe",
    city: "Buenos Aires", country: "Argentina",
    area: "Centro", areaHe: "מרכז העיר",
    category: "shopping", categoryHe: "קניות",
    tags: ["קניות", "שדרה"],
    descriptionHe: "שדרת הקניות המרכזית",
    priority: "medium",
    googleMapsUrl: "https://maps.google.com/?q=Avenida+Santa+Fe+Buenos+Aires",
    coordinates: { lat: -34.5956, lng: -58.3886 },
    source: "google-favorites",
  },
  {
    id: "ba-aeroparque",
    nameHe: "אארופארקה חורחה ניוברי",
    nameEn: "Aeroparque Jorge Newbery",
    city: "Buenos Aires", country: "Argentina",
    area: "Centro", areaHe: "מרכז העיר",
    category: "transport", categoryHe: "תחבורה",
    tags: ["נמל תעופה", "פנימי", "ברילוצ'ה"],
    descriptionHe: "נמל התעופה הפנימי — טיסות לברילוצ'ה — 4.4 ⭐",
    rating: 4.4, priority: "high",
    googleMapsUrl: "https://maps.google.com/?q=Aeroparque+Jorge+Newbery+Buenos+Aires",
    coordinates: { lat: -34.5592, lng: -58.4156 },
    relevantDays: [6],
    source: "google-favorites",
  },
  {
    id: "ba-alto-avellaneda",
    nameHe: "אלטו אבייאנדה שופינג",
    nameEn: "Alto Avellaneda Shopping",
    city: "Buenos Aires", country: "Argentina",
    area: "Centro", areaHe: "מרכז העיר",
    category: "shopping", categoryHe: "קניות",
    tags: ["קניון"],
    descriptionHe: "קניון — 4.3 ⭐",
    rating: 4.3, priority: "low",
    googleMapsUrl: "https://maps.google.com/?q=Alto+Avellaneda+Shopping+Buenos+Aires",
    coordinates: { lat: -34.6614, lng: -58.3644 },
    source: "google-favorites",
  },
  {
    id: "ba-casino",
    nameHe: "קזינו בואנוס איירס",
    nameEn: "Casino Buenos Aires",
    city: "Buenos Aires", country: "Argentina",
    area: "Centro", areaHe: "מרכז העיר",
    category: "casino", categoryHe: "קזינו",
    tags: ["קזינו"],
    descriptionHe: "קזינו בואנוס איירס — 4.2 ⭐",
    rating: 4.2, priority: "low",
    googleMapsUrl: "https://maps.google.com/?q=Casino+Buenos+Aires",
    coordinates: { lat: -34.6201, lng: -58.3642 },
    source: "google-favorites",
  },

  // ─── Tigre ────────────────────────────────────────────────────────────────
  {
    id: "tigre",
    nameHe: "טיגרה",
    nameEn: "Tigre",
    city: "Tigre", country: "Argentina",
    area: "טיגרה", areaHe: "טיגרה",
    category: "dayTrip", categoryHe: "טיול יום",
    tags: ["טיול יום", "דלתא", "טבע"],
    descriptionHe: "יעד לטיול יום מבואנוס — דלתא הפרנה",
    priority: "medium",
    googleMapsUrl: "https://maps.google.com/?q=Tigre+Buenos+Aires+Argentina",
    coordinates: { lat: -34.4259, lng: -58.5799 },
    source: "google-favorites",
  },

  // ─── Rosario ──────────────────────────────────────────────────────────────
  {
    id: "ros-flag-monument",
    nameHe: "מונומנט הדגל הלאומי",
    nameEn: "National Flag Monument",
    city: "Rosario", country: "Argentina",
    area: "מרכז רוסאריו", areaHe: "מרכז רוסאריו",
    category: "attraction", categoryHe: "אטרקציה",
    tags: ["דגל", "היסטוריה", "אנדרטה"],
    descriptionHe: "המונומנט הלאומי של הדגל הארגנטינאי — 4.7 ⭐",
    rating: 4.7, priority: "high",
    googleMapsUrl: "https://maps.google.com/?q=National+Flag+Monument+Rosario",
    coordinates: { lat: -32.9477, lng: -60.6304 },
    source: "google-favorites",
  },
  {
    id: "ros-independencia-park",
    nameHe: "פארק אינדפנדנסיה",
    nameEn: "Independencia Park",
    city: "Rosario", country: "Argentina",
    area: "מרכז רוסאריו", areaHe: "מרכז רוסאריו",
    category: "park", categoryHe: "פארק",
    tags: ["פארק", "גדול"],
    descriptionHe: "פארק הינדפנדנסיה — 4.6 ⭐",
    rating: 4.6, priority: "medium",
    googleMapsUrl: "https://maps.google.com/?q=Independencia+Park+Rosario",
    coordinates: { lat: -32.9553, lng: -60.6427 },
    source: "google-favorites",
  },
  {
    id: "ros-espana-park",
    nameHe: "פארק ספאניה",
    nameEn: "España Park",
    city: "Rosario", country: "Argentina",
    area: "מרכז רוסאריו", areaHe: "מרכז רוסאריו",
    category: "park", categoryHe: "פארק",
    tags: ["פארק", "נהר"],
    descriptionHe: "פארק על שפת הנהר — 4.7 ⭐",
    rating: 4.7, priority: "medium",
    googleMapsUrl: "https://maps.google.com/?q=España+Park+Rosario",
    coordinates: { lat: -32.9432, lng: -60.6363 },
    source: "google-favorites",
  },
  {
    id: "ros-newells",
    nameHe: "ניואלס אולד בויס",
    nameEn: "Newell's Old Boys",
    city: "Rosario", country: "Argentina",
    area: "כדורגל / מסי", areaHe: "כדורגל / מסי",
    category: "attraction", categoryHe: "אטרקציה",
    tags: ["מסי", "כדורגל", "ילדות"],
    descriptionHe: "הקבוצה של מסי בילדותו — 4.6 ⭐",
    rating: 4.6, priority: "high",
    googleMapsUrl: "https://maps.google.com/?q=Newell%27s+Old+Boys+Rosario",
    coordinates: { lat: -32.9648, lng: -60.6527 },
    source: "google-favorites",
  },

  // ─── Bariloche ────────────────────────────────────────────────────────────
  {
    id: "brc-alberto",
    nameHe: "אל בוליצ'ה דה אלברטו",
    nameEn: "El Boliche de Alberto",
    city: "Bariloche", country: "Argentina",
    area: "מרכז ברילוצ׳ה", areaHe: "מרכז ברילוצ׳ה",
    category: "restaurant", categoryHe: "מסעדה",
    tags: ["פארייה", "בשר", "מומלץ"],
    descriptionHe: "מסעדה ארגנטינאית מומלצת בברילוצ'ה — 4.6 ⭐",
    rating: 4.6, priority: "high",
    address: "Villegas 347, Bariloche",
    googleMapsUrl: "https://maps.google.com/?q=El+Boliche+de+Alberto+Bariloche",
    coordinates: { lat: -41.1349, lng: -71.3077 },
    relevantDays: [7, 8, 9, 10],
    source: "google-favorites",
  },

  // ─── Colonia del Sacramento ───────────────────────────────────────────────
  {
    id: "col-city",
    nameHe: "קולוניה דל סקרמנטו",
    nameEn: "Colonia del Sacramento",
    city: "Colonia del Sacramento", country: "Uruguay",
    area: "העיר העתיקה", areaHe: "העיר העתיקה",
    category: "attraction", categoryHe: "אטרקציה",
    tags: ["UNESCO", "עיר עתיקה", "יום טיול"],
    descriptionHe: "העיר העתיקה — יעד לטיול יום מבואנוס",
    priority: "high",
    googleMapsUrl: "https://maps.google.com/?q=Colonia+del+Sacramento+Uruguay",
    coordinates: { lat: -34.4671, lng: -57.8401 },
    source: "trip-plan",
  },
  {
    id: "col-barrio-historico",
    nameHe: "הרובע ההיסטורי",
    nameEn: "Barrio Histórico",
    city: "Colonia del Sacramento", country: "Uruguay",
    area: "העיר העתיקה", areaHe: "העיר העתיקה",
    category: "attraction", categoryHe: "אטרקציה",
    tags: ["UNESCO", "היסטוריה", "אבן"],
    descriptionHe: "הרובע ההיסטורי — מורשת עולמית UNESCO",
    priority: "high",
    googleMapsUrl: "https://maps.google.com/?q=Barrio+Histórico+Colonia+del+Sacramento",
    coordinates: { lat: -34.4734, lng: -57.8457 },
    source: "google-favorites",
  },
  {
    id: "col-calle-suspiros",
    nameHe: "רחוב האנחות",
    nameEn: "Calle de los Suspiros",
    city: "Colonia del Sacramento", country: "Uruguay",
    area: "העיר העתיקה", areaHe: "העיר העתיקה",
    category: "attraction", categoryHe: "אטרקציה",
    tags: ["רחוב", "אבן", "ציורי"],
    descriptionHe: "רחוב האנחות המפורסם — 4.7 ⭐",
    rating: 4.7, priority: "high",
    googleMapsUrl: "https://maps.google.com/?q=Calle+de+los+Suspiros+Colonia",
    coordinates: { lat: -34.4742, lng: -57.8463 },
    source: "google-favorites",
  },
  {
    id: "col-lighthouse",
    nameHe: "המגדלור",
    nameEn: "Colonia del Sacramento Lighthouse",
    city: "Colonia del Sacramento", country: "Uruguay",
    area: "העיר העתיקה", areaHe: "העיר העתיקה",
    category: "attraction", categoryHe: "אטרקציה",
    tags: ["מגדלור", "נוף"],
    descriptionHe: "המגדלור של קולוניה — 4.6 ⭐",
    rating: 4.6, priority: "high",
    googleMapsUrl: "https://maps.google.com/?q=Colonia+del+Sacramento+Lighthouse",
    coordinates: { lat: -34.4744, lng: -57.8473 },
    source: "google-favorites",
  },
  {
    id: "col-tapera-enrique",
    nameHe: "לה טאפרה דה אנריקה",
    nameEn: "La tapera de Enrique",
    city: "Colonia del Sacramento", country: "Uruguay",
    area: "מסעדות", areaHe: "מסעדות",
    category: "restaurant", categoryHe: "מסעדה",
    tags: ["מסעדה", "קולוניה"],
    descriptionHe: "מסעדה בקולוניה — 4.8 ⭐",
    rating: 4.8, priority: "high",
    googleMapsUrl: "https://maps.google.com/?q=La+tapera+de+Enrique+Colonia+del+Sacramento",
    coordinates: null,
    source: "google-favorites",
  },
  {
    id: "col-bruma",
    nameHe: "ברומה",
    nameEn: "Bruma",
    city: "Colonia del Sacramento", country: "Uruguay",
    area: "מסעדות", areaHe: "מסעדות",
    category: "restaurant", categoryHe: "מסעדה",
    tags: ["מסעדה משפחתית"],
    descriptionHe: "מסעדה משפחתית — 4.8 ⭐",
    rating: 4.8, priority: "high",
    googleMapsUrl: "https://maps.google.com/?q=Bruma+Colonia+del+Sacramento",
    coordinates: null,
    source: "google-favorites",
  },
  {
    id: "col-viejo-barrio",
    nameHe: "ויחו בריו",
    nameEn: "Viejo Barrio",
    city: "Colonia del Sacramento", country: "Uruguay",
    area: "מסעדות", areaHe: "מסעדות",
    category: "restaurant", categoryHe: "מסעדה",
    tags: ["מסעדה"],
    descriptionHe: "מסעדה בקולוניה — 4.5 ⭐",
    rating: 4.5, priority: "medium",
    googleMapsUrl: "https://maps.google.com/?q=Viejo+Barrio+Colonia+del+Sacramento",
    coordinates: null,
    source: "google-favorites",
  },
  {
    id: "col-souvenirs",
    nameHe: "סובנירס אורוגוואי",
    nameEn: "Souvenirs Uruguay",
    city: "Colonia del Sacramento", country: "Uruguay",
    area: "קניות", areaHe: "קניות",
    category: "shopping", categoryHe: "קניות",
    tags: ["מזכרות", "קניות"],
    descriptionHe: "חנות מזכרות — 4.5 ⭐",
    rating: 4.5, priority: "medium",
    googleMapsUrl: "https://maps.google.com/?q=Souvenirs+Uruguay+Colonia+del+Sacramento",
    coordinates: null,
    source: "google-favorites",
  },
];

/** Generate Google Maps search URL for places without a direct link */
export function getGoogleMapsUrl(place: MapPlace): string {
  if (place.googleMapsUrl) return place.googleMapsUrl;
  return `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(place.nameEn)}`;
}
